


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class Actualizar extends javax.swing.JFrame {
String tabla;
String id2;
Controlador cone= new Controlador();
    public Actualizar() {
        initComponents();
    }
    public Actualizar(String seleccion,int id){
    initComponents();
    String[] opciones=null;
    id2=String.valueOf(id);
    tabla=seleccion;
    campoid.setText(id2);
    //Seleccionar los campos necesarios segun la tabla escogida
    switch(seleccion){
        case "productos" -> opciones=new String[]{"Nombre","Precio","Categoria_ID","Proveedor_ID"};
        case "empleados" -> opciones=new String[]{"Nombre","Salario"};
        case "categorias" -> opciones=new String[]{"Nombre"};
        case "clientes" -> opciones=new String[]{"Nombre","Email"};
        case "pedidos" -> opciones=new String[]{"Cliente_ID","Fecha"};
        case "proveedores" -> opciones=new String[]{"Nombre","Dirección","Teléfono"};
        case "detallespedido" -> opciones=new String[]{"Pedido_ID","Producto_ID","Cantidad"};
        case "ventas" -> opciones=new String[]{"Cliente_ID","Producto_ID","Cantidad","Fecha","Empleado_ID"};
        default -> System.out.println("Error");
    }
    //Combobox con todos los campos salvo la id
    for (String opcione : opciones) {
        System.out.println(opcione);
        dato.addItem(opcione);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aceptar = new javax.swing.JButton();
        texto = new javax.swing.JLabel();
        dato = new javax.swing.JComboBox<>();
        campoid = new javax.swing.JTextField();
        nombreid = new javax.swing.JLabel();
        nuevovalor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        aceptar.setBackground(new java.awt.Color(102, 255, 102));
        aceptar.setText("ACEPTAR");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        texto.setText("Nuevo valor:");

        dato.setName(""); // NOI18N

        campoid.setEditable(false);

        nombreid.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(nombreid))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dato, 0, 139, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(texto)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(campoid)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(nuevovalor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(aceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(texto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevovalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void actualizar(){
String consulta="";
String valor=nuevovalor.getText();
String datos=dato.getSelectedItem().toString();
if(datos.equals("Nombre")||datos.equals("Fecha")||datos.equals("Direccion")||datos.equals("Telefono")||datos.equals("Email")){
valor="'"+valor+"'";
}
//Crear consulta    
switch(tabla){
        case "productos" -> consulta = "UPDATE PRODUCTOS SET "+datos+" = "+valor+" WHERE ID = " + id2;
        case "empleados" -> consulta = "UPDATE EMPLEADOS SET "+datos+" = "+valor+" WHERE ID = " + id2;
        case "categorias" -> consulta = "UPDATE CATEGORIAS SET "+datos+" = "+valor+" WHERE ID = " + id2;
        case "clientes" -> consulta = "UPDATE CLIENTES SET "+datos+" = "+valor+" WHERE ID = " + id2;
        case "pedidos" -> consulta = "UPDATE PEDIDOS SET "+datos+" = "+valor+" WHERE ID = " + id2;
        case "proveedores" -> consulta = "UPDATE PROVEEDORES SET "+datos+" = "+valor+" WHERE ID = " + id2;
        case "detallespedido" -> consulta = "UPDATE DETALLESPEDIDO SET "+datos+" = "+valor+" WHERE ID = " + id2;
        case "ventas" -> consulta = "UPDATE VENTAS SET "+datos+" = "+valor+" WHERE ID = " + id2;
        default -> System.out.println("Error");
    }
//Intentar la consulta
try {
        cone.conectar();
        cone.update(consulta);
        JOptionPane.showMessageDialog(null, "Se ha actualizado correctamente", "Número ingresado", JOptionPane.INFORMATION_MESSAGE);
    } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("ERROR"+ex.toString());
        }
}
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        actualizar();
        dispose();
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField campoid;
    private javax.swing.JComboBox<String> dato;
    private javax.swing.JLabel nombreid;
    private javax.swing.JTextField nuevovalor;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
