
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class Inicio extends javax.swing.JFrame {
Controlador controlador = new Controlador();
    /**
     * Creates new form bASE
     */
    public Inicio() {
        initComponents();
        jTextField1.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sentencias = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        conectar = new javax.swing.JButton();
        cursores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sentencias.setBackground(new java.awt.Color(255, 204, 255));
        sentencias.setText("SENTENCIAS DML");
        sentencias.setEnabled(false);
        sentencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentenciasActionPerformed(evt);
            }
        });
        getContentPane().add(sentencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 235, 60));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 30, 30));

        salir.setBackground(new java.awt.Color(255, 204, 255));
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 235, 60));

        conectar.setBackground(new java.awt.Color(255, 204, 255));
        conectar.setText("CONECTAR LA BASE DE DATOS");
        conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarActionPerformed(evt);
            }
        });
        getContentPane().add(conectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 235, 60));

        cursores.setBackground(new java.awt.Color(255, 204, 255));
        cursores.setText("CURSORES");
        cursores.setEnabled(false);
        cursores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoresActionPerformed(evt);
            }
        });
        getContentPane().add(cursores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 235, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void conectar(){
    //Intentar conectar con la base de datos
        try {
            controlador.conectar();
            jTextField1.setBackground(Color.green);
            sentencias.setEnabled(true);
            cursores.setEnabled(true);
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("ERROR"+ex.toString());
        }
}
public void salir (){
    //Intentar desconectarse de la base de datos
    try {
            controlador.desconectar();
            dispose();
        } catch (SQLException | IOException ex) {
            System.out.println("ERROR"+ex.toString());
        }
}
    private void conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarActionPerformed
        conectar();
    }//GEN-LAST:event_conectarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
    //Desconectar de la base de datos y cerrar la aplicación    
    try {
        controlador.desconectar();
        
    } catch (SQLException | IOException ex) {
        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
    }
    salir();
    }//GEN-LAST:event_salirActionPerformed

    private void sentenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentenciasActionPerformed
       Sentencias_DML s1 = new Sentencias_DML();
       s1.setVisible(true);
    }//GEN-LAST:event_sentenciasActionPerformed

    private void cursoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoresActionPerformed
        Cursores a= new Cursores(controlador);
        a.setVisible(true);
    }//GEN-LAST:event_cursoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conectar;
    private javax.swing.JButton cursores;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton salir;
    private javax.swing.JButton sentencias;
    // End of variables declaration//GEN-END:variables
}
